version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kairos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - kairos-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: kairos-backend
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - kairos-network

  redis:
    image: redis:7.2-alpine
    container_name: kairos-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - kairos-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: kairos-keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/${DB_NAME}_keycloak
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME: ${KEYCLOAK_PUBLIC_HOSTNAME}
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - kairos-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: kairos-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"   # AMQP protocol port (for microservices connection)
      - "${RABBITMQ_INTERFACE_PORT}:15672" # Web management interface port (Dashboard)
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - kairos-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  kairos-network:
    driver: bridge