services:
  mysql:
    image: mysql:8.0
    container_name: kairos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d  # <- adiciona isso
    networks:
      - kairos-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: kairos-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - kairos-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: kairos-keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/${DB_NAME}_keycloak
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - kairos-network

volumes:
  mysql_data:
  redis_data:

networks:
  kairos-network:
    driver: bridge