package br.com.artheus.kairos.risk;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

class RiskCalculatorPropertiesTest {

    private static Validator validator;

    @BeforeAll
    static void setUp() {
        try (ValidatorFactory factory = Validation.buildDefaultValidatorFactory()) {
            validator = factory.getValidator();
        }
    }

    // Default valid fixtures to simplify test setup
    private final RiskCalculatorProperties.RainThresholds validRain =
            new RiskCalculatorProperties.RainThresholds(10.0, 20.0, 30.0);

    private final RiskCalculatorProperties.WindThresholds validWind =
            new RiskCalculatorProperties.WindThresholds(15.0, 30.0, 50.0);

    private final RiskCalculatorProperties.Thresholds validThresholds =
            new RiskCalculatorProperties.Thresholds(validRain, validWind);

    @Test
    @DisplayName("Should pass validation when the sum of weights is exactly 1.0")
    void shouldPassWhenWeightsSumIsExact() {
        RiskCalculatorProperties properties = new RiskCalculatorProperties(0.7, 0.3, 1.5, validThresholds);
        assertThat(validator.validate(properties)).isEmpty();
    }

    @Test
    @DisplayName("Should pass validation when the sum of weights is slightly higher but within delta tolerance")
    void shouldPassWhenWeightsSumIsSlightlyHigherWithinDelta() {
        RiskCalculatorProperties properties = new RiskCalculatorProperties(0.70001, 0.30001, 1.5, validThresholds);
        assertThat(validator.validate(properties)).isEmpty();
    }

    @Test
    @DisplayName("Should pass validation when the sum of weights is slightly lower but within delta tolerance")
    void shouldPassWhenWeightsSumIsSlightlyLowerWithinDelta() {
        RiskCalculatorProperties properties = new RiskCalculatorProperties(0.69999, 0.29999, 1.5, validThresholds);
        assertThat(validator.validate(properties)).isEmpty();
    }

    @Test
    @DisplayName("Should fail validation when the sum of weights exceeds the allowed delta ceiling")
    void shouldFailWhenWeightsSumIsTooHigh() {
        RiskCalculatorProperties properties = new RiskCalculatorProperties(0.8, 0.3, 1.5, validThresholds);
        Set<ConstraintViolation<RiskCalculatorProperties>> violations = validator.validate(properties);

        assertThat(violations).hasSize(1);
        assertThat(violations.iterator().next().getPropertyPath().toString()).isEqualTo("weightsSumValid");
    }

    @Test
    @DisplayName("Should fail validation when the sum of weights is below the allowed delta floor")
    void shouldFailWhenWeightsSumIsTooLow() {
        RiskCalculatorProperties properties = new RiskCalculatorProperties(0.5, 0.3, 1.5, validThresholds);
        Set<ConstraintViolation<RiskCalculatorProperties>> violations = validator.validate(properties);

        assertThat(violations).hasSize(1);
        assertThat(violations.iterator().next().getPropertyPath().toString()).isEqualTo("weightsSumValid");
    }

    @Test
    @DisplayName("Should fail validation when required threshold attributes are null")
    void shouldFailWhenRequiredAttributesAreNull() {
        RiskCalculatorProperties properties = new RiskCalculatorProperties(0.5, 0.5, 1.5, null);
        Set<ConstraintViolation<RiskCalculatorProperties>> violations = validator.validate(properties);

        assertThat(violations).hasSize(1);
        assertThat(violations.iterator().next().getPropertyPath().toString()).isEqualTo("thresholds");
    }

    @Test
    @DisplayName("Should fail validation when numeric weight values are zero or negative")
    void shouldFailWhenValuesAreZeroOrNegative() {
        RiskCalculatorProperties properties = new RiskCalculatorProperties(-0.5, 0.5, 1.5, validThresholds);
        Set<ConstraintViolation<RiskCalculatorProperties>> violations = validator.validate(properties);

        // Fails on @Positive climateWeight AND the custom weightsSumValid validation
        assertThat(violations).hasSize(2);
    }

    @Test
    @DisplayName("Should cover autogenerated record methods to achieve 100% code coverage")
    void shouldCoverRecordInfrastructureMethods() {
        RiskCalculatorProperties props1 = new RiskCalculatorProperties(0.7, 0.3, 1.5, validThresholds);
        RiskCalculatorProperties props2 = new RiskCalculatorProperties(0.7, 0.3, 1.5, validThresholds);

        // Assertions covering equals, hashCode, and toString for the main record and its nested records
        assertThat(props1.toString()).contains("climateWeight=0.7");
        assertThat(props1).isEqualTo(props2);
        assertThat(props1.hashCode()).isEqualTo(props2.hashCode());

        assertThat(validRain.toString()).contains("medium=10.0");
        assertThat(validRain).isEqualTo(new RiskCalculatorProperties.RainThresholds(10.0, 20.0, 30.0));
        assertThat(validRain.hashCode()).isNotZero();

        assertThat(validWind.toString()).contains("medium=15.0");
        assertThat(validWind).isEqualTo(new RiskCalculatorProperties.WindThresholds(15.0, 30.0, 50.0));
        assertThat(validWind.hashCode()).isNotZero();
    }
}